
services:
  ubuntu-ssh:
    build: .
    container_name: ubuntu
    ports:
      - "2200:22"
      - "5173:5173"
      - "3001:3001"
    environment:
      - ROOT_PASSWORD=123456
    volumes:
      - ./workspace:/workspace
      - ./home:/home
      - ./root:/root
    working_dir: /workspace
    restart: unless-stopped
    stdin_open: true
    tty: true 